export const REQUEST_API_DATA = 'REQUEST_API_DATA';
export const GET_API_DATA = 'GET_API_DATA';
export const SAVE_API_DATA = 'SAVE_API_DATA';
export const SET_API_DATA_LOADING_TRUE = 'SET_API_DATA_LOADING_TRUE';
export const SET_API_DATA_LOADING_FALSE = 'SET_API_DATA_LOADING_FALSE';
export const SET_API_DATA_ERROR = 'SET_API_DATA_ERROR';
